services:
  backend:
    image: debian:bookworm-slim  
    container_name: go-backend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - /home/driannsa/goseperate/backend:/app
      - /home/driannsa/goseperate/backend/extracted:/app/extracted
      - /home/driannsa/goseperate/backend/uploads:/app/uploads
    # command: ["/app/myapp"]
    ports:
      - "9330:9330"
